apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: ecommerce
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "local-secret-key"
  DATABASE_URL: "postgres://ecom:ecompass@host.docker.internal:5432/ecom"
