apiVersion: v1
kind: Service
metadata:
  name: django-web
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: django-web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
